#! /usr/bin/env python
# encoding: utf-8
# mittorn, 2018

from waflib import Logs
import os

top = '.'
vk_sdk_dir = os.environ.get('VULKAN_SDK')

def options(opt):
	return

def configure(conf):
	conf.check(lib=[f'{vk_sdk_dir}/Lib/vulkan-1'], uselib_store='VK')
	conf.check(lib=[f'{vk_sdk_dir}/Lib/SDL2'], uselib_store='SDL2')
	return

def build(bld):
	libs = [ 'engine_includes', 'werror', 'VK', 'SDL2']
	# on PSVita do not link any libraries that are already in the main executable, but add the includes target
	if bld.env.DEST_OS == 'psvita':
		libs += [ 'sdk_includes' ]
	else:
		libs += [ 'public', 'M' ]

	bld.shlib(source   = bld.path.ant_glob('*.c'),
		target   = 'ref_vk',
		includes = [
			'.',
			f'{vk_sdk_dir}/Include/'
		],
		defines  = 'REF_DLL=1',
		use      = libs,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
