#! /usr/bin/env python
# encoding: utf-8
# Vulkan renderer build script

from waflib import Logs
import os

top = '.'

def options(opt):
	grp = opt.add_option_group('ref_vk options')
	grp.add_option('--enable-vulkan-validation', action='store_true', dest='VULKAN_VALIDATION', default=False,
		help='enable Vulkan validation layers [default: %(default)s]')
	grp.add_option('--vulkan-sdk', action='store', dest='VULKAN_SDK', default=None,
		help='path to Vulkan SDK (required for Windows)')
	return

def configure(conf):
	conf.env.VULKAN_VALIDATION = conf.options.VULKAN_VALIDATION
	conf.env.VULKAN_SDK = conf.options.VULKAN_SDK
	
	if conf.env.DEST_OS2 == 'android':
		# Android requires Vulkan
		conf.check_cc(lib='vulkan')
	else:
		# Desktop platforms - check for Vulkan SDK
		# First, try custom SDK path
		if conf.env.VULKAN_SDK:
			conf.start_msg('Configuring Vulkan by path')
			vk_path = conf.env.VULKAN_SDK
			
			# Check include path
			inc_path = os.path.join(vk_path, 'Include')
			if os.path.exists(inc_path):
				conf.env.INCLUDES_VULKAN = [inc_path]
			else:
				# Try common locations
				inc_paths = [
					os.path.join(vk_path, 'include'),
					os.path.join(vk_path, 'include', 'vulkan'),
				]
				for p in inc_paths:
					if os.path.exists(p):
						conf.env.INCLUDES_VULKAN = [p]
						break
			
			# Check library path
			if conf.env.DEST_OS == 'win32':
				lib_name = 'vulkan-1.lib'
			else:
				lib_name = 'libvulkan.so'
			
			lib_paths = [
				os.path.join(vk_path, 'Lib'),
				os.path.join(vk_path, 'lib'),
				os.path.join(vk_path, 'lib32'),
				os.path.join(vk_path, 'lib64'),
			]
			
			found_lib = False
			for lib_path in lib_paths:
				if os.path.exists(os.path.join(lib_path, lib_name)):
					conf.env.LIBPATH_VULKAN = [lib_path]
					conf.env.LIB_VULKAN = [lib_name.replace('.lib', '').replace('lib', '')]
					found_lib = True
					break
			
			if found_lib:
				conf.env.VULKAN_FOUND = True
				conf.end_msg('found')
			else:
				conf.end_msg('not found')
		else:
			# Try to find vulkan via pkg-config first
			if conf.env.HAVE_PKGCONFIG:
				if conf.check_cfg(package='vulkan', uselib_store='VULKAN', args=['--cflags', '--libs']):
					conf.env.VULKAN_FOUND = True
			# Fallback: try direct linking
			if not conf.env.VULKAN_FOUND:
				conf.check_cc(lib='vulkan', mandatory=False)

def build(bld):
	libs = ['ref_common', 'engine_includes', 'werror']
	
	# Platform-specific libraries
	if bld.env.DEST_OS == 'android':
		libs += ['log']
	else:
		libs += ['public', 'M']
	
	# Source files
	source = bld.path.ant_glob([
		'*.c',
	])
	
	# Defines
	defines = ['XASH_VULKAN=1']
	if bld.env.VULKAN_VALIDATION:
		defines.append('VULKAN_VALIDATION=1')
	
	# Libraries
	link_libs = []
	if bld.env.VULKAN_FOUND:
		link_libs = ['vulkan']
	link_libs += ['dl']
	
	# Includes for custom Vulkan SDK and ref/common
	includes = ['.', '../common', '../../public', '../gl', '../../engine']
	if bld.env.INCLUDES_VULKAN:
		includes += bld.env.INCLUDES_VULKAN
	
	# Build target
	bld.shlib(
		features = 'c cxx',
		target = 'ref_vk',
		source = source,
		includes = includes,
		defines = defines + ['REF_DLL=1'],
		use = libs,
		uselib = ['VULKAN'] if bld.env.VULKAN_FOUND else [],
		install_path = bld.env.LIBDIR,
	)

	# Create shaders directory placeholder
	bld.env.INCLUDES += [bld.path.abspath() + '/shaders']
