#! /usr/bin/env python
# encoding: utf-8
# mittorn, 2018

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	bld.shlib(
		source   = bld.path.ant_glob(['*.c']),
		includes = ['.'],
		target   = 'ref_gl4',
		defines  = 'REF_DLL=1',
		use      = 'engine_includes sdk_includes werror public M',
		install_path = bld.env.LIBDIR
	)
